#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OS=$(uname)
QUIET=0

usage() { echo "Usage: $0 [-q]" 1>&2; exit 1; }

while getopts ":q" o; do
  case "${o}" in
    q) QUIET=1;;
    *) usage;;
  esac
done
shift $((OPTIND-1))

if [ $QUIET -eq 0 ]; then echo -n "Updating config..."; fi
pushd $DIR 1> /dev/null
git pull 1> /dev/null
if [ $QUIET -eq 0 ]; then
  if [ $? -eq 0 ]; then
    if [ "$OS" == "Darwin" ]; then
      echo $' [ \e[0;32mOK\e[0m ]'
    else
      echo -e " [ \e[0;32mOK\e[0m ]"
    fi
  else
    if [ "$OS" == "Darwin" ]; then
      echo $' [ \e[0;31mFAILED\e[0m ]'
    else
      echo -e " [ \e[0;31mFAILED\e[0m ]"
    fi
  fi
fi
popd 1> /dev/null

